CompileFlags:
  Add: [-std=c++2b, -Wall, -pedantic]

Diagnostics:
  ClangTidy:
    Add: [
      bugprone-*, modernize-*, cppcoreguidelines-*, 
      performance-*, readability-*, abseil-*,
      google-*, misc-*
      ]
    Remove: [
      bugprone-easily-swappable-parameters,
      bugprone-narrowing-conversions,
      cppcoreguidelines-special-member-functions,
      cppcoreguidelines-narrowing-conversions,
      misc-definitions-in-headers,
      misc-non-private-member-variables-in-classes,
      modernize-use-trailing-return-type,
      readability-named-parameter,
      readability-convert-member-functions-to-static,
      raedability-make-magic-numbers,
      google-readability-namespace-comments,
      readability-make-member-function-const,
      cppcoreguidelines-avoid-magic-numbers
      ]
    UnusedIncludes: Strict

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes
